version: '1.0.0'
services:
    nav:
        container_name: nav
        build:
            context: ./
            dockerfile: ./Dockerfile
        environment:
        # 时区
        - TZ=Asia/Shanghai
        volumes:
        # 映射配置文件
        - ./config:/app/config
        ports:
            - "9000:80"
        restart: unless-stopped
