version: '1.0.0'
services:
    nav:
        container_name: nav
        build:
            context: ./
            dockerfile: ./Dockerfile
        environment:
        # 时区
        - TZ=Asia/Shanghai
        # 数据库配置
        - DATABASE_URI=sqlite:///app/data/data.db
        # 配置文件
        ports:
            - "9000:80"
        restart: unless-stopped
