[project]
name = ""
version = ""
description = ""
authors = [
    { name = "moxiaoying", email = "768091671@qq.com" },
]
dependencies = [
    "tortoise-orm<=0.19.3",
    "fastapi<=0.99.1",
    "fastapi-pagination>=0.12.6",
    "loguru>=0.7.0",
    "httpx>=0.24.1",
    "BeautifulSoup4>=4.12.2",
    "fastapi-jwt>=0.1.12",
    "passlib>=1.7.4",
    "bcrypt>=4.0.1",
    "Jinja2>=3.1.2",
]
requires-python = ">=3.10"
license = { text = "MIT" }

[tool]
[tool.pdm]
[[tool.pdm.source]]
url = "https://pypi.org/simple"
verify_ssl = true


[tool.pdm.dev-dependencies]
dev = [
    "faker>=19.2.0",
]

[build-system]
requires = ["pdm-pep517>=1.0.0"]
build-backend = "pdm.pep517.api"
